### Perceptron

In [1]:
import numpy as np

In [28]:
class Perceptron(object):
    def __init__(self, input_size, lr=1, epochs=10):
        self.W = np.zeros(input_size+1)
        self.epochs = epochs
        self.lr = lr
    def activation(self, x):
        return 1 if x >= 0 else 0
    def predict(self, x):
        x = np.insert(x, 0, 1)
        z = self.W.T.dot(x)
        a = self.activation(z)
        return a
    def fit(self, X, d):
        for _ in range(self.epochs):
            for i in range(d.shape[0]):
                y = self.predict(X[i])
                e = d[i] - y
                self.W = self.W + self.lr * e * np.insert(X[i], 0, 1)

In [29]:
mp = Perceptron(5)
mp.activation(-10)

0

In [30]:
mp.W

array([0., 0., 0., 0., 0., 0.])

In [31]:
x = np.asarray([1,2,3,4,5])
mp.predict(x)

1

In [32]:
x = np.asarray([-1,2,-3,4,-5])
mp.predict(x)

1

In [33]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
d = np.array([0,0,0,1])
perceptron = Perceptron(input_size = 2)
perceptron.fit(X, d)
print(perceptron.W)

[-3.  2.  1.]


In [35]:
perceptron.predict(np.array([1,1]))

1

In [36]:
#XOR için yapılan çalışma
X = np.array([[0,0], [0,1], [1,0], [1,1]])
d = np.array([0,1,1,0])
perceptron_2 = Perceptron(input_size = 2)
perceptron_2.fit(X, d)
print(perceptron_2.W)

[ 0. -1.  0.]


In [43]:
perceptron_2.predict(np.array([1,0])) #Hatalı sonuç verdi

0

#### Fonksiyonlar
    Activasyon: fonksiyonu outputları sınıflandırmamıza yarıyor. Yaptığımız işlemler sonucu çıkan değerin hangi sınıfta yer aldığını belirliyoruz
    
    Predict: fonksiyonu eğittiğimiz modelle verilen girdinin, sonucunu tahmin etmemizi sağlar
    
    Fit: model için en uygun W değelerini hesapladığımız fonksiyondur, yani modeli eğittiğimiz fonksiyon
    

#### 40 imza
    Her öğrencinin belli sayıda imzalarını alınır örneğin; Her öğrenciden 3 imza bu bizim X değişkenimiz olur. d ise bu aldığımız her 3 imzanın hangi öğrenciye ait olduğunu tuttuğumuz bir değişken olur.

    x1 = öğrenci
    X = [ [x1_imza_1,  x1_imza_2,  x1_imza_3] ]
    d = [x1]

    Tahmin etmek istediğimiz öğrencinin bir imzasını alır predict fonsiyonuna aktarırız, predict fonksiyonu bize verilen imzanın hangi öğrenciye ait olduğunu tahmin eder.

### Error
    Veri kümemizde 10 adet veri varsa bunların 3'ünü test için 7'sini eğitim amaçlı olarak kullanabiliriz. 7'si ile perceptron'u eğitiriz, sonucu bildiğimiz 3 veriyi perceptron kullanarak tahmin ettiririz. Sonucunu bildiğimiz gerçek verilerle, perceptron'un sonuçlarını karşılaştırarak model hatasını elde edebiliriz.